### ISSUE TITLE
Internal Server Error

### ISSUE THREAD

**Issue by darkhax** [Diluv/API#17]
The user end point `http://api.diluv-dev.com/v1/users` will sometimes throw a 500 internal server error.

**Comment by Insidious611** [comment]
I would suggest looking at the Apache logs to see more details about the
error.

**Comment by darkhax** [comment]
@Insidious611 I don't think I have access to the logs at this stage. This is a known issue though, we've all been able to reproduce it. Just putting it here as a reminder to fix it.

**Comment by Insidious611** [comment]
It's just a very vague error description. A 500 ISE could be practically
anything. However, given what you said in another issue about it exposing
too much data, I suspect maybe a timeout?

**Comment by lclc98** [comment]
It is the API throwing the error not nginx

**Comment by lclc98** [comment]
Same issue as #14
