### ISSUE TITLE
Bloated user endpoint

### ISSUE THREAD

**Issue by darkhax** [Diluv/API#18]
The user end point seems a bit bloated, as it includes all of the projects for every registered user. I am worried that this end point could be used maliciously, in terms of getting usernames to spam/harass users, or "DDOS" our API by making this expensive call. We should reconsider this end point. 

http://api.diluv-dev.com/v1/users

**Comment by lclc98** [comment]
I have currently removed projects until we have worked out a better system. It will probably be a endpoint of the user
