### ISSUE TITLE
Incorrect permission serialization

### ISSUE THREAD

**Issue by gegy1000** [Diluv/API#21]
`ProjectPermissionType` has a few methods which pack or unpack permissions from an int using the passed ids as bit indices.
https://github.com/Diluv/API/blob/c8b56452a0e2a45290c533ac45c21b7a01c0d927/src/main/java/com/diluv/api/permission/project/ProjectPermissionTypes.java#L42-L54
This works fine assuming all the ids are <=32, however they extend far past that. To properly store all the current ids, a 256bit int would be required.

**Comment by lclc98** [comment]
Yeah, I ran across this issue, I wasn't thinking when making it and realise the limitation when testing. We have decided to move away from packing ints.

**Comment by lclc98** [comment]
I have changed it to not have this issue.
